//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FightingFeather.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColumnVisibility_MERON {
            get {
                return ((bool)(this["ColumnVisibility_MERON"]));
            }
            set {
                this["ColumnVisibility_MERON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColumnVisibility_BET_M {
            get {
                return ((bool)(this["ColumnVisibility_BET_M"]));
            }
            set {
                this["ColumnVisibility_BET_M"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColumnVisibility_WALA {
            get {
                return ((bool)(this["ColumnVisibility_WALA"]));
            }
            set {
                this["ColumnVisibility_WALA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColumnVisibility_BET_W {
            get {
                return ((bool)(this["ColumnVisibility_BET_W"]));
            }
            set {
                this["ColumnVisibility_BET_W"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColumnVisibility_INITIAL_BET_DIF {
            get {
                return ((bool)(this["ColumnVisibility_INITIAL_BET_DIF"]));
            }
            set {
                this["ColumnVisibility_INITIAL_BET_DIF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColumnVisibility_PAREHAS {
            get {
                return ((bool)(this["ColumnVisibility_PAREHAS"]));
            }
            set {
                this["ColumnVisibility_PAREHAS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColumnVisibility_LOGRO {
            get {
                return ((bool)(this["ColumnVisibility_LOGRO"]));
            }
            set {
                this["ColumnVisibility_LOGRO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColumnVisibility_PAGO {
            get {
                return ((bool)(this["ColumnVisibility_PAGO"]));
            }
            set {
                this["ColumnVisibility_PAGO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColumnVisibility_WINNER {
            get {
                return ((bool)(this["ColumnVisibility_WINNER"]));
            }
            set {
                this["ColumnVisibility_WINNER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColumnVisibility_RATE {
            get {
                return ((bool)(this["ColumnVisibility_RATE"]));
            }
            set {
                this["ColumnVisibility_RATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColumnVisibility_RATE_EARNINGS {
            get {
                return ((bool)(this["ColumnVisibility_RATE_EARNINGS"]));
            }
            set {
                this["ColumnVisibility_RATE_EARNINGS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColumnVisibility_FEE {
            get {
                return ((bool)(this["ColumnVisibility_FEE"]));
            }
            set {
                this["ColumnVisibility_FEE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColumnVisibility_TOTAL_PLASADA {
            get {
                return ((bool)(this["ColumnVisibility_TOTAL_PLASADA"]));
            }
            set {
                this["ColumnVisibility_TOTAL_PLASADA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColumnVisibility_RATE_AMOUNT {
            get {
                return ((bool)(this["ColumnVisibility_RATE_AMOUNT"]));
            }
            set {
                this["ColumnVisibility_RATE_AMOUNT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColumnVisibility_WINNERS_EARN {
            get {
                return ((bool)(this["ColumnVisibility_WINNERS_EARN"]));
            }
            set {
                this["ColumnVisibility_WINNERS_EARN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColumnVisibility_SETTINGS {
            get {
                return ((bool)(this["ColumnVisibility_SETTINGS"]));
            }
            set {
                this["ColumnVisibility_SETTINGS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReminderEnabled {
            get {
                return ((bool)(this["ReminderEnabled"]));
            }
            set {
                this["ReminderEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string MainFormWindowState {
            get {
                return ((string)(this["MainFormWindowState"]));
            }
            set {
                this["MainFormWindowState"] = value;
            }
        }
    }
}
